proxies:
- name: Hysteria2-01
  type: hysteria2
  server: www.838491.xyz
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
- name: Hysteria2-01 [IPv4直连]
  type: hysteria2
  server: 62.210.8.122
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
- name: Hysteria2-02
  type: hysteria2
  server: www.838491.xyz
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
- name: Hysteria2-02 [IPv4直连]
  type: hysteria2
  server: 62.210.8.122
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
- name: Hysteria2-03
  type: hysteria2
  server: www.838491.xyz
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
- name: Hysteria2-03 [IPv4直连]
  type: hysteria2
  server: 62.210.8.122
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
- name: Hysteria2-04
  type: hysteria2
  server: www.838491.xyz
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
- name: Hysteria2-04 [IPv4直连]
  type: hysteria2
  server: 62.210.8.122
  port: 13377
  password: dongtaiwang.com
  sni: www.838491.xyz
  skip-cert-verify: true
  alpn:
  - h3
  up: 11 mbps
  down: 55 mbps
  fast-open: true
